project:
  type: book
  output-dir: docs

book:
  title: "twri r-manual"
  author: "Michael Schramm"
  image: "images/logo-drop.png"
  repo-url: https://github.com/txwri/r-manual
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  original-date: "7/29/2022"
  date: today
  navbar: 
    logo: "images/logo-drop.png"
    search: true
    background: "#02233b"
    foreground: "#f6f6f6"
  chapters:
    - index.qmd
    - part: "R Basics"
      chapters:
        - intro.qmd
        - data_exploration.qmd
    - part: "Hydrology"
      chapters:
        - streamflow.qmd
        - stage-discharge.qmd
        - drainage-area-ratio.qmd
    - part: "Water Quality"
      chapters:
        - water-quality.qmd
        - load-duration.qmd
        - water-quality-statistics.qmd
    - part: "Geospatial"
      chapters:
        - maps.qmd
        - watershed-delineation.qmd
        - raster-summary.qmd
    - references.qmd
  page-footer:
    border: true
    left: |
      [Texas Water Resources Institute](https://twri.tamu.edu)
    right: |
      This work is licensed under</br>
      [CC BY-NC 4.0
      ![](https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1){style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"}
      ![](https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1){style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"}
      ![](https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1){style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"}](http://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1)

bibliography: references.yml
csl: https://raw.githubusercontent.com/TxWRI/csl/main/twri-technical-report.csl

format:
  html:
    # hyperlink functions in code blocks
    code-link: true
    # code block has grey background
    code-block-bg: true
    # blue bar on side of code box
    code-block-border-left: "#02233b"
    # wrap long lines of code
    code-overflow: wrap
    # theme css
    theme:
      light: css/twri_quarto.scss
    mainfont: Crimson Text
    monofont: Source Code Pro
    css: css/twri.scss
    # define figure sizing
    fig-width: 8
    fig-height: 5
    # footnotes go in the margin
    reference-location: margin
    
knitr: 
  opts_chunk: 
    dev: ragg_png
    dpi: 200



